[
  "Abhaya Libre ExtraBold",
  "Abhaya Libre Medium",
  "Abhaya Libre SemiBold",
  "Academy Engraved LET",
  "Adobe Blank",
  "Aksara Bali Galang",
  "Al Bayan",
  "Al Nile",
  "Al Tarikh",
  "Amatica SC",
  "American Typewriter",
  "Amiri Quran Colored",
  "AmstelvarAlpha",
  "Andale Mono",
  "Andika New Basic",
  "Apple Braille",
  "Apple Chancery",
  "Apple SD Gothic Neo",
  "Apple Symbols",
  "AppleGothic",
  "AppleMyungjo",
  "Arial",
  "Arial Black",
  "Arial Hebrew",
  "Arial Hebrew Scholar",
  "Arial Narrow",
  "Arial Rounded MT Bold",
  "Arial Unicode MS",
  "Arima Madurai",
  "Arimo Hebrew Subset",
  "Arimo Hebrew Subset Italic",
  "Athelas",
  "Avenir",
  "Avenir Next",
  "Avenir Next Condensed",
  "Ayuthaya",
  "BM HANNA_TTF",
  "Baghdad",
  "Baloo",
  "Baloo Bhai",
  "Baloo Bhaijaan",
  "Baloo Bhaina",
  "Baloo Chettan",
  "Baloo Da",
  "Baloo Paaji",
  "Baloo Tamma",
  "Baloo Tammudu",
  "Baloo Thambi",
  "Bangla MN",
  "Bangla Sangam MN",
  "Baskerville",
  "Be Vietnam",
  "Beirut",
  "Bhavuka",
  "Big Caslon",
  "Bodoni 72",
  "Bodoni 72 Oldstyle",
  "Bodoni 72 Smallcaps",
  "Bodoni Ornaments",
  "Bradley Hand",
  "Brush Script MT",
  "Bungee Color",
  "Butcherman Caps",
  "CantoraOne",
  "Chalkboard",
  "Chalkboard SE",
  "Chalkduster",
  "Charter",
  "Cherry Bomb",
  "Cochin",
  "Coda Caption",
  "Comic Sans MS",
  "Copperplate",
  "Corsiva Hebrew",
  "Courier",
  "Courier New",
  "Creepster Caps",
  "DIN Alternate",
  "DIN Condensed",
  "Damascus",
  "DecoType Naskh",
  "Decovar Alpha",
  "Devanagari MT",
  "Devanagari Sangam MN",
  "Dhyana",
  "Didot",
  "Digital Numbers",
  "Diwan Kufi",
  "Diwan Thuluth",
  "Droid Sans",
  "Ek Mukta",
  "Estedad-VF",
  "Euphemia UCAS",
  "Farah",
  "Farisi",
  "Figma Hand",
  "Fjord",
  "Font Awesome 5 Brands",
  "Font Awesome 5 Free",
  "Font Awesome 6 Brands",
  "Font Awesome 6 Free",
  "Fredoka One",
  "Futura",
  "Galvji",
  "Geeza Pro",
  "Geneva",
  "Gentium Basic",
  "Gentium Book Basic",
  "Georgia",
  "Gill Sans",
  "Grantha Sangam MN",
  "Gujarati MT",
  "Gujarati Sangam MN",
  "Gurmukhi MN",
  "Gurmukhi MT",
  "Gurmukhi Sangam MN",
  "Hannari",
  "HeadlandOne",
  "Heiti SC",
  "Heiti TC",
  "Helvetica",
  "Helvetica Neue",
  "Herculanum",
  "Hermeneus One",
  "Hind Colombo",
  "Hind Jalandhar",
  "Hind Kochi",
  "Hind Mysuru",
  "Hiragino Kaku Gothic Pro",
  "Hiragino Kaku Gothic ProN",
  "Hiragino Kaku Gothic Std",
  "Hiragino Kaku Gothic StdN",
  "Hiragino Maru Gothic Pro",
  "Hiragino Maru Gothic ProN",
  "Hiragino Mincho Pro",
  "Hiragino Mincho ProN",
  "Hiragino Sans",
  "Hiragino Sans GB",
  "Hoefler Text",
  "IM FELL DW Pica",
  "IM FELL DW Pica SC",
  "IM FELL Double Pica",
  "IM FELL Double Pica SC",
  "IM FELL English",
  "IM FELL English SC",
  "IM FELL French Canon",
  "IM FELL French Canon SC",
  "IM FELL Great Primer",
  "IM FELL Great Primer SC",
  "ITF Devanagari",
  "ITF Devanagari Marathi",
  "Impact",
  "InaiMathi",
  "Iowan Old Style",
  "JejuGothic",
  "JejuHallasan",
  "JejuMyeongjo",
  "Kailasa",
  "Kannada MN",
  "Kannada Sangam MN",
  "Kantumruy",
  "Kapakana",
  "Kdam Thmor",
  "Kefa",
  "Khmer MN",
  "Khmer Sangam MN",
  "KoPub Batang",
  "Kohinoor Bangla",
  "Kohinoor Devanagari",
  "Kohinoor Gujarati",
  "Kohinoor Telugu",
  "Kokonor",
  "Kokoro",
  "Krungthep",
  "KufiStandardGK",
  "Kyiv*Type Serif",
  "Kyiv*Type Titling",
  "KyivType Sans",
  "Lao MN",
  "Lao Muang Don",
  "Lao Muang Khong",
  "Lao Sangam MN",
  "Lao Sans Pro",
  "Ligconsolata",
  "Lohit Bengali",
  "Lohit Devanagari",
  "Lohit Tamil",
  "Lucida Grande",
  "Luminari",
  "Malayalam MN",
  "Malayalam Sangam MN",
  "Marion",
  "Marker Felt",
  "Material Icons",
  "Menlo",
  "Merge One",
  "Merienda One",
  "Mervale Script",
  "Miama",
  "Microsoft Sans Serif",
  "Mishafi",
  "Mishafi Gold",
  "Monaco",
  "Mplus 1p",
  "Mplus 1p Bold",
  "Mshtakan",
  "Muna",
  "Myanmar Khyay",
  "Myanmar MN",
  "Myanmar Sangam MN",
  "Myanmar Sans Pro",
  "NATS",
  "Nadeem",
  "Nanum Pen",
  "NanumGothic",
  "NanumGothicCoding",
  "NanumMyeongjo",
  "New Peninim MT",
  "Nico Moji",
  "Nikukyu",
  "Nosifer Caps",
  "Noteworthy",
  "Noto Color Emoji Compat Test",
  "Noto Looped Thai",
  "Noto Looped Thai UI",
  "Noto Sans Bengali UI",
  "Noto Sans Gujarati UI",
  "Noto Sans Hebrew Droid",
  "Noto Sans Hebrew New",
  "Noto Sans Kannada UI",
  "Noto Sans Malayalam UI",
  "Noto Sans PhagsPa",
  "Noto Sans Symbols2",
  "Noto Sans Tamil UI",
  "Noto Sans Telugu UI",
  "Noto Sans Thai UI",
  "Noto Sans Zawgyi",
  "Noto Serif Hmong Nyiakeng",
  "Noto Serif Tamil Slanted",
  "NotoSerifTamilSlanted",
  "NovaMono",
  "OFL Sorts Mill Goudy TT",
  "OdorMeanChey",
  "Open Sans Condensed",
  "Open Sans Hebrew",
  "Open Sans Hebrew Condensed",
  "Optima",
  "Oriya MN",
  "Oriya Sangam MN",
  "Otomanopee One",
  "Palatino",
  "Papyrus",
  "Party LET",
  "Pecita",
  "Phetsarath",
  "Phosphate",
  "PingFang HK",
  "PingFang SC",
  "PingFang TC",
  "Plantagenet Cherokee",
  "PoetsenOne",
  "Ponnala",
  "Porter Sans Block",
  "Post No Bills Colombo",
  "Post No Bills Colombo ExtraBold",
  "Post No Bills Colombo Light",
  "Post No Bills Colombo Medium",
  "Post No Bills Colombo SemiBold",
  "Post No Bills Jaffna",
  "Post No Bills Jaffna ExtraBold",
  "Post No Bills Jaffna Light",
  "Post No Bills Jaffna Medium",
  "Post No Bills Jaffna SemiBold",
  "RU Serius",
  "Raanana",
  "Rockwell",
  "Rounded Mplus 1c",
  "Rounded Mplus 1c Bold",
  "Rubik One",
  "STIX Two Math",
  "STIXGeneral",
  "STIXIntegralsD",
  "STIXIntegralsSm",
  "STIXIntegralsUp",
  "STIXIntegralsUpD",
  "STIXIntegralsUpSm",
  "STIXNonUnicode",
  "STIXSizeFiveSym",
  "STIXSizeFourSym",
  "STIXSizeOneSym",
  "STIXSizeThreeSym",
  "STIXSizeTwoSym",
  "STIXVariants",
  "STSong",
  "Saira ExtraCondensed",
  "Saira SemiCondensed",
  "Sana",
  "Sansation",
  "Sansation Light",
  "Sansita One",
  "Sathu",
  "Savoye LET",
  "Scheherazade",
  "SeoulHangang",
  "SeoulHangang CB",
  "SeoulHangang CBL",
  "SeoulHangang CEB",
  "SeoulHangang CL",
  "SeoulHangang CM",
  "SeoulNamsan",
  "SeoulNamsan CB",
  "SeoulNamsan CBL",
  "SeoulNamsan CEB",
  "SeoulNamsan CL",
  "SeoulNamsan CM",
  "Seravek",
  "Shree Devanagari 714",
  "SignPainter",
  "Signika Negative SC",
  "Signika SC",
  "Silom",
  "Sinhala MN",
  "Sinhala Sangam MN",
  "SirinStencil",
  "Sitara",
  "Skia",
  "Snell Roundhand",
  "Songti SC",
  "Songti TC",
  "Souliyo Unicode",
  "Source Sans Pro",
  "Source Serif Pro",
  "Spartan",
  "Strong",
  "Sudo Var",
  "Sukhumvit Set",
  "Superclarendon",
  "Supermercado",
  "Symbol",
  "System Font",
  "Tahoma",
  "Tamil MN",
  "Tamil Sangam MN",
  "Telugu MN",
  "Telugu Sangam MN",
  "Thabit",
  "TharLon",
  "Thonburi",
  "Times",
  "Times New Roman",
  "Trattatello",
  "Trebuchet MS",
  "Tuffy",
  "Verdana",
  "Waseem",
  "Webdings",
  "Wingdings",
  "Wingdings 2",
  "Wingdings 3",
  "Yaldevi Colombo",
  "Yaldevi Colombo ExtraLight",
  "Yaldevi Colombo Light",
  "Yaldevi Colombo Medium",
  "Yaldevi Colombo SemiBold",
  "Yinmar",
  "Zapf Dingbats",
  "Zapfino",
  "jsMath-cmbx10",
  "jsMath-cmex10",
  "jsMath-cmmi10",
  "jsMath-cmr10",
  "jsMath-cmsy10",
  "jsMath-cmti10",
];
